_target_: pipelines.QwenImageMaskFlow
_recursive_: true

pretrained_model: Qwen/Qwen-Image-Edit-2511
cfg_dropout: 0.1

mask_dilation_kernel: 75
mask_blur_kernel: 75
mask_blur_sigma: 45.0
mask_edge_width: 90  # dilate 45, erode 45

mask_loss_weight: 1.0
edge_loss_weight: 0.0

# If null, the noise scheduler will be initialized with diffusers FlowMatchEulerDiscreteScheduler
# else, use schedulers.flow_matching.RectifiedFlowMatchingScheduler
scheduler:
  _target_: schedulers.MaskFlowScheduler
  weighting_scheme: logit_normal
  logit_normal_mean: 0.0
  logit_normal_std: 1.0
  mode_scale: 1.29
  base_image_seq_len: 256
  base_shift: 0.5
  max_image_seq_len: 8192
  max_shift: 0.9
  shift: 1.0
  shift_power: 1
  time_shift_type: exponential
  use_dynamic_shifting: true
  unmask_with: noisy_source
