_target_: data_module.MaskEditDataset

image_root: "MaskImageEdit-S"
data_file: "outputs/data_cache/demo.jsonl"
data_load_ratio: 1
max_resolution: 1048576
divisible_by: 16
enable_aspect_bucket: false
enable_prompt_truncation: true
replace_prompt_placeholder_with: "the area masked by image 2"