timestamp: ${now:%Y%m%d-%H%M%S}

project_name: project-train
output_dir: outputs/experiments/${project.project_name}/${project.timestamp}
checkpoint_dir: ${project.output_dir}/checkpoints
evaluation_dir: ${project.output_dir}/evaluations
log_dir: ${project.output_dir}/logs