defaults:
  - evalset: mask_edit
  - pipeline: qwenimage_mask_flow
  - project: evaluation
  - adapter: lora
  - _self_

pipe_configs: ${pipeline}
eval_data_configs: ${evalset}
lora_configs: ${adapter}

base_seed: 42
resume_from: null

text_cfg_scale: 4.0
mask_cfg_scale: 4.0
num_inference_steps: 50

eval_with_position_prompt: false

hydra:
  run:
    dir: ${project.output_dir}/hydra-configs
