defaults:
  - pipeline: qwenimage_mask_flow
  - adapter: lora
  - _self_


timestamp: ${now:%Y%m%d-%H%M%S}
resume_from: ""
safetensors_dir: ""

hydra:
  run:
    dir: outputs/inference/${timestamp}/hydra-configs