defaults:
  - trainset: mask_edit_multi
  - evalset: mask_edit_multi
  - optimizer: prodigy
  - pipeline: qwenimage_mask_flow
  - project: train
  - adapter: dmd_lora
  - lr_scheduler: null
  - trainer: dmd
  - _self_

hydra:
  run:
    dir: ${project.output_dir}/hydra-configs
  output_subdir: .hydra/rank-${oc.env:RANK,0}
  job_logging:
    handlers:
      file:
        filename: ${hydra.runtime.output_dir}/${hydra.job.name}-rank-${oc.env:RANK,0}.log
