defaults:
  - trainset: mask_edit
  - evalset: mask_edit
  - optimizer: prodigy
  - pipeline: qwenimage_edit_plus_2511
  - project: train
  - adapter: lora
  - lr_scheduler: null
  - trainer: lora
  - _self_


hydra:
  run:
    dir: ${project.output_dir}/hydra-configs